#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FileService.Droid.Resource", IsApplication=true)]

namespace FileService.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::FileService.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::FileService.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::FileService.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::FileService.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::FileService.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::FileService.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int blue = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int body = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int button_blue = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int card_background = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int card_error = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int card_heading = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int card_secondary = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int card_text = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int danger = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int darkGrey = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int holo_blue_dark = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int holo_blue_light = 2131034138;
			
			// aapt resource value: 0x7f05000e
			public const int icon_primary = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int icon_secondary = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int icon_tertiary = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int lightGrey = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int offBlack = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int panel_backgrond = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int panel_text = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int primary_text = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int red = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int secondary_text = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int test_outcome_fail = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int test_outcome_pass = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int test_outcome_unknown = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int white = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cancel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pass_fail_progress = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int upload = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int uploaded = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int warning_icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int seekbar = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Seekbar = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
