#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FileService.Droid.Resource", IsApplication=true)]

namespace FileService.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040011
			public const int body = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int button_blue = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int card_background = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int card_error = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int card_heading = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int card_secondary = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int card_text = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int danger = 2130968594;
			
			// aapt resource value: 0x7f040004
			public const int darkGrey = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040019
			public const int holo_blue_dark = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int holo_blue_light = 2130968602;
			
			// aapt resource value: 0x7f04000e
			public const int icon_primary = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int icon_secondary = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int icon_tertiary = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int lightGrey = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int offBlack = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int panel_backgrond = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int panel_text = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int primary_text = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int red = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int secondary_text = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int test_outcome_fail = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int test_outcome_pass = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int test_outcome_unknown = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int white = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cancel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pass_fail_progress = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int upload = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int uploaded = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int warning_icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int seekbar = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Seekbar = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
